FROM python:3.8-slim-buster

WORKDIR /lib-svc

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY  public/ .

EXPOSE 2323

ENV FLASK_APP=public.api
ENV FLASK_ENV=development

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=2323"]