FROM python:3.8-slim-buster

WORKDIR /lib-svc

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY admin/ .

EXPOSE 2324

ENV FLASK_APP=api.py

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=2324"]